name: thorsent
markdown: redcarpet
pygments: true
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!--more-->
exclude: [node_modules, Gruntfile.js, package.json, karma.conf.js, tests, README.md]